spring:
  datasource:
    password: ${JDBC_DATABASE_PASSWORD}
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
  sql:
    init:
      mode: never
  config:
    activate:
      on-profile: prod


jwt:
  secret: ${JWT_SECRET}
  secretRefresh: ${JWT_REFRESH_SECRET}
  secretPasswordReset: ${JWT_PASSWORD_RESET_SECRET}
  secretPasswordUpdate: ${JWT_PASSWORD_UPDATE_SECRET}
  expiration: 7200
  expirationRefresh: 604800
  expirationPasswordReset: 86400
  expirationPasswordUpdate: 3600
  header: Authorization

cloudinary:
  cloudName: dtpc0u9df
  apiKey: 655195143842919
  apiSecret: ylUvwt1553Lx1FdWnnIKWAl5rE8

url:
  server: http://localhost:8080
  client: http://localhost:3000
clientChangePasswordPath: changePassword
serverChangePasswordPath: api/v1/auth/resetPassword